import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Providers from "./lib/Providers";
import RenderModal from "@/components/ModalsComponent/Index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trendy Fashion",
  description: "Generated by trendy fashion",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="min-h-screen">{children}</div>
          <Toaster />
          <RenderModal />
        </Providers>
      </body>
    </html>
  );
}
