import "./globals.css";
import type { Metadata } from "next";
import Providers from "./lib/Providers";
import RenderModal from "@/components/ModalsComponent/Index";
import { SessionProvider } from "next-auth/react";
export const metadata: Metadata = {
  title: "Trendy Fashion",
  description: "Generated by trendy fashion",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Providers>
            <div className="min-h-screen">{children}</div>
            <RenderModal />
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
