import React from "react";
import type { Metadata } from "next";
import Sidebar from "@/components/shared/AdminNav/AdminSidebar/Sidebar";
import AdminNavbar from "@/components/shared/AdminNav/AdminNavbar/AdminNavbar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="bg-gray-200 min-h-screen">
      <AdminNavbar />
      <Sidebar />
      {children}
    </div>
  );
};

export default DashboardLayout;
